FROM frolvlad/alpine-oraclejdk8:slim
VOLUME /tmp
ADD europeanintegration-0.0.1-SNAPSHOT.jar europeanintegration.jar
RUN sh -c 'touch /europeanintegration.jar'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /europeanintegration.jar" ]
